### ISSUE TITLE
如何能让target控件高亮显示？setOverlayTarget(false)不起作用

### ISSUE THREAD

**Issue by gaoyl87** [binIoter/GuideView#1]
你好，如何能让target控件高亮显示？setOverlayTarget(false)不起作用

**Comment by binIoter** [comment]
是因为缺少这行代码导致的，加上就可以了～
        //修复目标view不高亮显示的bug
        if (!mOverlayTarget) {
            canvas.clipRect(mTargetRect, Region.Op.DIFFERENCE);
        }

**Comment by gaoyl87** [comment]
原来的代码是
canvas.drawRect(mFullingRect, mFullingPaint);
        if (!mOverlayTarget) {
            canvas.drawRect(mTargetRect, mTargetPaint);
        }

现在改成
canvas.drawRect(mFullingRect, mFullingPaint);
        if (!mOverlayTarget) {
            canvas.clipRect(mTargetRect, Region.Op.DIFFERENCE);
        }
还是不起作用

**Comment by binIoter** [comment]
看最新源代码，注意代码的位置

发自 网易邮箱大师
在2016年06月21日 11:40，FreedomCoderELong 写道:

原来的代码是
canvas.drawRect(mFullingRect, mFullingPaint);
if (!mOverlayTarget) {
canvas.drawRect(mTargetRect, mTargetPaint);
}

现在改成
canvas.drawRect(mFullingRect, mFullingPaint);
if (!mOverlayTarget) {
canvas.clipRect(mTargetRect, Region.Op.DIFFERENCE);
}
还是不起作用
