### ISSUE TITLE
如果高亮的布局上有button 怎样去监听该button的点击事件

### ISSUE THREAD

**Issue by daiwenbo88** [binIoter/GuideView#14]
如果需要通过监听高亮布局上的button的点击事件来关闭该高亮的的显示 如何才能在外面监听到该button的点击事件 而不是在Component的实现类中去监听

**Comment by binIoter** [comment]
高亮的时候默认不遮罩张台，所以高亮区域是不可以处理点击事件的，否则就违背了遮罩的原则
