### ISSUE TITLE
Component接口高亮布局点击消失

### ISSUE THREAD

**Issue by fanxl12** [binIoter/GuideView#15]
看项目里面点击高亮区域，弹出一个吐司，怎么实现点击让整个引导区消失呢？有没有方法设置？

**Comment by binIoter** [comment]
在吐丝弹出的地方调用dismiss方法即可

发自网易邮箱大师
在2016年09月27日 10:30，fxl 写道:

看项目里面点击高亮区域，弹出一个吐司，怎么实现点击让整个引导区消失呢？有没有方法设置？

**Comment by fanxl12** [comment]
Component里面拿不到Guide对象吧

**Comment by fanxl12** [comment]
@binIoter Component里面拿不到Guide对象吧

**Comment by hegaojian** [comment]
我也是需要这个需求，在吐丝弹出的地方调用不到dismiss方法啊，带佬
