### ISSUE TITLE
怎么对整个activity或者fragment高亮

### ISSUE THREAD

**Issue by fanxl12** [binIoter/GuideView#16]
怎么对整个activity界面高亮，不指定targetView，看demo里面好像都指定了targetview

**Comment by binIoter** [comment]
页面本身就是高亮的，我们做的是遮罩，要是全部高亮就不需要遮罩啊，或者你的targetview设置成你的根布局

发自网易邮箱大师
在2016年09月27日 11:18，fxl 写道:

怎么对整个activity界面高亮，不指定targetView，看demo里面好像都指定了targetview
