### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by kongnanlive** [binIoter/GuideView#2]
你看看这个项目跟你的有什么区别，https://github.com/hongyangAndroid/Highlight

**Comment by binIoter** [comment]
您好，对比hongyang大神的作品，这个组件库不但可以实现一个页面多个引导提示，逐个显示，引导层view支持点击事件，还可以支持引导层显示隐藏回调局部遮罩，不遮罩，目标view高亮不高亮等等，看源代码的注释可以看出来所有功能～
