### ISSUE TITLE
在多个fragment中遮罩混乱

### ISSUE THREAD

**Issue by justdoitJX** [binIoter/GuideView#23]
一个activity中有4个fragment，有两个fragment设置了遮罩，但连续点这四个fragment，另外两个没有设置遮罩的fragment有时也会出现遮罩，求怎么解决

**Comment by binIoter** [comment]
如果fragment采用replace方式应该不会有这个问题吧？如果采用hide，show，那就要自己处理引导逻辑了


发自网易邮箱大师
在2017年01月04日 18:55，Jx 写道:

一个activity中有4个fragment，有两个fragment设置了遮罩，但连续点这四个fragment，另外两个没有设置遮罩的fragment有时也会出现遮罩，求怎么解决

**Comment by justdoitJX** [comment]
现在首页是viewpager中放的4个fragment，引导逻辑怎么处理呢

**Comment by binIoter** [comment]
Viewpager 有自己的默认初始化页数设置，你可以设置成1


发自网易邮箱大师
在2017年01月04日 18:55，Jx 写道:

一个activity中有4个fragment，有两个fragment设置了遮罩，但连续点这四个fragment，另外两个没有设置遮罩的fragment有时也会出现遮罩，求怎么解决

**Comment by justdoitJX** [comment]
恩   好的   已经解决了   用setUserVisibleHint去控制了    谢谢
