### ISSUE TITLE
请问如何一个页面多个高亮的区域

### ISSUE THREAD

**Issue by peiniwan** [binIoter/GuideView#26]
请问如何实现一个页面多个高亮的区域，而且高亮的形状不一样？

**Comment by binIoter** [comment]
请参见demo




发自网易邮箱大师
在2017年05月06日 17:01，peiniwan 写道：

请问如何实现一个页面多个高亮的区域，而且高亮的形状不一样？

**Comment by gincoo** [comment]
你好 ，求助，我没看到在哪里设置的，ViewActivity是嘛？
