### ISSUE TITLE
遮罩的位置不对怎么调整位置

### ISSUE THREAD

**Issue by wanyt** [binIoter/GuideView#27]
如题

**Comment by lori-zhao** [comment]
实例化Component对象的时候，你可以通过重写getXOffset方法和getYOffset方法来调节细微的针对某个遮罩的偏移量，如果需要大范围的更改遮罩产生的位置，你可以在类库中，重写MaskView中的onLayout方法（比如我的效果是默认在屏幕最底下用一个imageview来显示遮罩的内容）。
