### ISSUE TITLE
你好,在一个带有下拉刷新的页面对某个view遮罩位置不对,请问有什么解决办法吗?

### ISSUE THREAD

**Issue by AndroidDevo** [binIoter/GuideView#37]
进入一个页面首先需要请求数据会自动下拉刷新,请求数据完成后再进行操作

**Comment by Missyouag** [comment]
延迟加载，postDelayed（难以预估时间。。。）或者监听布局是否加载完成

**Comment by binIoter** [comment]
可以监听viewTree，例如
header_imgbtn.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
      @Override
      public void onGlobalLayout() {
        //在这里判断一下只展示一次，因为回调可能执行多次
      }
    });
