### ISSUE TITLE
减少使用内存

### ISSUE THREAD

**Issue by Missyouag** [binIoter/GuideView#38]
https://github.com/binIoter/GuideView/blob/f606f748f3660033f61ea7e74199fe92b08670a7/guideview/src/main/java/com/blog/www/guideview/MaskView.java#L61

 mEraserBitmap = Bitmap.createBitmap(size.x, size.y, Bitmap.Config.ALPHA_8);

 canvas.drawBitmap(mEraserBitmap, 0, 0, mFullingPaint);

**Comment by binIoter** [comment]
是的，谢谢您的宝贵建议




| |
张斌
|
|
邮箱：bin_iot@163.com
|

签名由 网易邮箱大师 定制

在2017年12月12日 11:22，爱玩 写道：

https://github.com/binIoter/GuideView/blob/f606f748f3660033f61ea7e74199fe92b08670a7/guideview/src/main/java/com/blog/www/guideview/MaskView.java#L61

mEraserBitmap = Bitmap.createBitmap(size.x, size.y, Bitmap.Config.ALPHA_8);

canvas.drawBitmap(mEraserBitmap, 0, 0, mFullingPaint);
