### ISSUE TITLE
Component里面的布局点击的时候，怎么把遮盖层关掉啊？

### ISSUE THREAD

**Issue by hegaojian** [binIoter/GuideView#40]

**Comment by hegaojian** [comment]
把Component里面布局的点击事件去掉就好了，不要给布局设置点击事件，特瞄滴就是这么简单！

**Comment by zgmd** [comment]
接口回调

**Comment by binIoter** [comment]
setautodissmiss true




| |
张斌
邮箱：bin_iot@163.com
|

签名由 网易邮箱大师 定制

在2018年12月06日 13:03，zgmd 写道：

接口回调
