### ISSUE TITLE
虚拟导航键显示隐藏导致的bug

### ISSUE THREAD

**Issue by SiberiaDante** [binIoter/GuideView#46]
Demo也存在的问题：1.虚拟导航键显示隐藏会导致高亮区域无限扩大；2.虚拟导航键显示时打开遮罩，再隐藏虚拟键屏幕底部会有空白。
有大佬解决的吗

**Comment by moonstr** [comment]
我也碰到过类似问题，最底部部分会被虚拟键盘覆盖

**Comment by binIoter** [comment]
最新版已经解决了
