### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by dongzhimo** [binIoter/GuideView#48]
能不能给高亮位置单独设置点击事件？？

**Comment by binIoter** [comment]
目前是全局处理点击事件maskView.setOnTouchListener(this);你要扩展很简单，只要这样
mConfiguration.mTargetView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                Toast.makeText(activity,"haha",Toast.LENGTH_LONG).show();
                return true;
            }
        });
