### ISSUE TITLE
可以自定义提示图片吗？

### ISSUE THREAD

**Issue by qianshengta** [binIoter/GuideView#51]
![1565061093(1)](https://user-images.githubusercontent.com/29747624/62508638-f6382780-b83a-11e9-83c5-4f0cc1e3b6bd.jpg)
我的设计图提示图片是这样的，跟库里的不一样，设计师坚持要用它的，那么这个提示图片可以自己设置吗？

**Comment by binIoter** [comment]
![image](https://user-images.githubusercontent.com/15646030/62509107-81fe8380-b83c-11e9-9b3c-5ad10f32071a.png)

**Comment by qianshengta** [comment]
好的 谢谢  我去demo看看怎么搞

**Comment by qianshengta** [comment]
但是一个新问题，上面那张图其实是两个页面的，就是传统的一个mainFragment+4个主界面的。所以上面的其实是分上下两个Fragment的，mainFragment是下面的一排按钮+上面的子fragment，所以这横跨两个fragment的引导层该怎么加？@binloter

**Comment by binIoter** [comment]
目前只支持一次展示一个引导层，当前的引导层消失后，在展示下一个。如果这样可以满足需求，你可以在mainFragment中消失后通知上边的fragment展示，或者直接把对应要高亮的view设置tag，然后在activity里的decoreview通过findViewByTag去找到你的控件，去处理

**Comment by qianshengta** [comment]
好的
