### ISSUE TITLE
在三星手机上面 蒙版的颜色怎么修改都不能改变，会一直是白色的

### ISSUE THREAD

**Issue by pengjunhong** [binIoter/GuideView#52]

**Comment by lishicong** [comment]
需要关闭你的硬件加速
`<activity
            android:name="com.demo.aty.SimpleGuideViewActivity"
            android:hardwareAccelerated="false"
            android:screenOrientation="portrait" />`

**Comment by pjh520** [comment]
已处理 将MaskView类中mEraserBitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888); 改成Bitmap.Config.ARGB_8888 成功了

**Comment by binIoter** [comment]
感谢反馈，我说下背景，由于灰色蒙层是基于一张Bitmap实现的，考虑到内存的占用，优先考虑用Bitmap.Config.ALPHA_8质量参数，相比Bitmap.Config.ARGB_8888 ，内存占用仅为其1/4。我会测试一下三星手机的问题，在看如何优化

**Comment by pjh520** [comment]
是的 框架很好用！

**Comment by binIoter** [comment]
👍多交流，多反馈问题，多提建议🤝
