### ISSUE TITLE
为什么不显示文字

### ISSUE THREAD

**Issue by kyo2001lee** [binIoter/GuideView#7]
如题，就是高亮区域出来了，但是文字和图片没有显示出来是复制Demo中的

**Comment by kyo2001lee** [comment]
高亮区域怎么才可以缩小啊

**Comment by kyo2001lee** [comment]
高亮区域和空间的大小不一样，大了很多~

**Comment by binIoter** [comment]
文字和图片显示不出来，你检查一下显示方向
@Override public int getAnchor() {
    return Component.ANCHOR_LEFT;
  }
这个方法

高亮区域的大小可以通过padding属性自定义设置
