### ISSUE TITLE
无法支持暗夜模式和常规模式

### ISSUE THREAD

**Issue by MichaelDuanChina** [binIoter/GuideView#79]
无法根据系统当前是暗夜模式还是常规模式，来自动读取常规图片和-night文件夹中的图片。是否有解决思路？

**Comment by slender-le** [comment]
奇怪，你怎么能看到代码




--
发自我的网易邮箱手机智能版



在 2021-05-08 10:02:16，MichaelDuanChina ***@***.***> 写道：


Closed #79.
