### ISSUE TITLE
你好，Demo在低版本中无法显示高亮区域，我这边测试的是4.4.2.

### ISSUE THREAD

**Issue by weitie1990** [binIoter/GuideView#8]
![6 zsbi 8 jp0 aey6g kw](https://cloud.githubusercontent.com/assets/15317623/17835456/7feda936-679f-11e6-9189-84e747ce15b7.png)

**Comment by binIoter** [comment]
我的手机就是4.4.2的没问题的，你换真机试一下，不行你说一下真机手机型号

**Comment by weitie1990** [comment]
非常感谢你的回复，不好意思我打错字了，应孩是4.2.2(api17)的版本，真机我用的酷派手机测过也一样，真机具体啥型号不知道了，借的别人的，真机也是4.2.2的版本。

**Comment by Loofer** [comment]
你好，4.3上面无法显示高亮区域

**Comment by binIoter** [comment]
应该是模拟器的问题，换真机测试吧

**Comment by duanhao** [comment]
android:hardwareAccelerated="false"
 由于这个BUG是硬加速造成的，所以关闭硬加速可以解决问题，但是会出现卡帧问题，毕竟没有了硬加速，降低了性能。

**Comment by LOWANGA** [comment]
怎么解决的低版本不高亮问题
